'use client';

import * as React from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, FileText } from 'lucide-react';
import { toast } from 'sonner';
import { api, ApiError } from '@/lib/api';
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Label,
} from '@/components/ui/core';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/overlay';
import { EmptyState, ErrorState, TableSkeleton } from '@/components/ui/states';
import { formatDateTime, formatNumber } from '@/lib/utils';

const FILTERS = [
  { value: 'all', label: 'All URLs' },
  { value: 'indexed_confirmed', label: 'Indexed (confirmed)' },
  { value: 'not_confirmed', label: 'Not confirmed indexed' },
  { value: 'failed', label: 'Failed' },
  { value: 'blocked', label: 'Blocked / invalid' },
  { value: 'pending', label: 'Pending' },
];

export default function ReportsPage() {
  const queryClient = useQueryClient();
  const [projectId, setProjectId] = React.useState('all');
  const [filter, setFilter] = React.useState('all');

  const projectsQuery = useQuery({
    queryKey: ['projects', { includeArchived: true }],
    queryFn: () => api.projects.list({ includeArchived: true }),
  });

  const reportsQuery = useQuery({
    queryKey: ['reports'],
    queryFn: () => api.reports.list(),
    // Reports are generated by a worker; poll while any are still running.
    refetchInterval: (query) =>
      query.state.data?.items.some((report) => report.status === 'QUEUED' || report.status === 'GENERATING')
        ? 4_000
        : false,
  });

  const create = useMutation({
    mutationFn: () =>
      api.reports.create({
        filter,
        ...(projectId === 'all' ? {} : { projectId }),
      }),
    onSuccess: () => {
      toast.success('Report queued.');
      void queryClient.invalidateQueries({ queryKey: ['reports'] });
    },
    onError: (error: unknown) =>
      toast.error(error instanceof ApiError ? error.message : 'Could not queue the report.'),
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold sm:text-2xl">Reports</h1>
        <p className="text-sm text-muted-foreground">
          CSV exports with per-URL status, validation details and index-check history.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Generate a report</CardTitle>
          <CardDescription>Large exports are built in the background.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="report-project">Project</Label>
              <Select value={projectId} onValueChange={setProjectId}>
                <SelectTrigger id="report-project">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All projects</SelectItem>
                  {projectsQuery.data?.items.map((project) => (
                    <SelectItem key={project.id} value={project.id}>
                      {project.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="report-filter">Rows</Label>
              <Select value={filter} onValueChange={setFilter}>
                <SelectTrigger id="report-filter">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {FILTERS.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex items-end">
              <Button className="w-full" loading={create.isPending} onClick={() => create.mutate()}>
                <FileText className="h-4 w-4" />
                Generate CSV
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="overflow-hidden">
        <CardHeader>
          <CardTitle>Your reports</CardTitle>
          <CardDescription>Download links expire after seven days.</CardDescription>
        </CardHeader>
        <CardContent className="px-0 sm:px-0">
          {reportsQuery.isLoading ? (
            <TableSkeleton rows={4} />
          ) : reportsQuery.isError ? (
            <ErrorState error={reportsQuery.error} onRetry={() => void reportsQuery.refetch()} />
          ) : reportsQuery.data?.items.length === 0 ? (
            <EmptyState
              icon={FileText}
              title="No reports yet"
              description="Generate one above to export your URL data."
            />
          ) : (
            <ul className="divide-y">
              {reportsQuery.data?.items.map((report) => (
                <li
                  key={report.id}
                  className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6"
                >
                  <div className="min-w-0">
                    <p className="text-sm font-medium">
                      {report.projectName ?? 'All projects'} · {report.filter}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {formatDateTime(report.createdAt)}
                      {report.rowCount !== null ? ` · ${formatNumber(report.rowCount)} rows` : ''}
                      {report.errorMessage ? ` · ${report.errorMessage}` : ''}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge
                      variant={
                        report.status === 'READY'
                          ? 'success'
                          : report.status === 'FAILED'
                            ? 'destructive'
                            : 'secondary'
                      }
                    >
                      {report.status}
                    </Badge>
                    {report.downloadUrl ? (
                      <Button asChild size="sm" variant="outline">
                        <a href={report.downloadUrl}>
                          <Download className="h-4 w-4" />
                          Download
                        </a>
                      </Button>
                    ) : null}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
